name              'cpu'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Manage CPU Governor on linux'
source_url        'https://github.com/sous-chefs/cpu'
issues_url        'https://github.com/sous-chefs/cpu/issues'
chef_version      '>= 15.3'
version           '3.0.14'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 22.04'
