name 'cpu'
maintainer 'Guilhem Lettron'
maintainer_email 'guilhem@lettron.fr'
license 'Apache-2.0'
description 'Manage CPU Governor on linux'
version '2.0.0'
supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'fedora'
supports 'scientific'
supports 'oracle'
supports 'amazon'

source_url 'https://github.com/redguide/cpu'
issues_url 'https://github.com/redguide/cpu/issues'
chef_version '>= 12.5'
